# Generated by Django 4.0.3 on 2022-04-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('year_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('bio', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='time',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='chef',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.chef'),
        ),
    ]
