# Generated by Django 4.0.3 on 2022-04-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_chef_alter_restaurant_time_restaurant_chef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='time',
            new_name='openhour',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='chef',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.IntegerField(default=None, null=True)),
                ('chef', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.chef')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dishes',
            field=models.ManyToManyField(to='restaurants.dishes'),
        ),
    ]
